name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Run Mocha / Chai tests
    steps:
      - uses: actions/checkout@v1
      - name: test
          run: npm test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "dylanlarrivee@gmail.com"
          usedocker: false

