name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: npm install
        run: npm test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "dylanlarrivee@gmail.com"
          usedocker: false

# name: Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   test:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [ 10, 12, 14]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install
#     - run: npm test
  
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy to Heroku
#       env:
#         HEROKU_API_TOKEN: ${{secrets.HEROKU_API_KEY}}
#         HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
#       if: github.ref == 'refs/heads/master' && job.status == 'success'
#       run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master